---
title: "U.S Presidential elections: geographic and demographic trends "
output:
 # html_document: default
#pdf_document: default
  prettydoc::html_pretty:
    theme: leonids
    # theme: leonids
    toc: yes
---




    
```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
```


## **U.S Presidential elections: geographic and demographic trends**

<style>
p {
    text-align: justify;
    text-justify: inter-word;
}
</style>
Every four years, US citizens exercise their civic rights through presidential elections. Unlike many nations worldwide, which use direct elections based on the national popular vote ('one person, one vote') to elect their respective presidents, the United States presidential system utilizes indirect elections through the Electoral College. This decentralized system mirrors the structure of other elections in the United States, where each state plays a significant role in the electoral process. (NCSL,2023)

In light of the influential role played by each state and the potential for demographic shifts within a four-year time frame, we employ available data to explore voting trends across individual states alongside demographic changes, with a particular emphasis on race and ethnicity. Two primary questions guide our analysis:

-   How have party preferences evolved over time across different geographic regions of the United States?

-   What impact do changes in demographic trends wield on election outcomes within specific states?

We rely on data from the MIT Election Data Science Lab to address these inquiries. Additionally, we utilize publicly available US census data, accessed via the tidycensus R package. 

### Navigating our dashboard 

At the top left of this page, you'll find three buttons:

-   Overview: This page, offering a general overview.
-   Voting Trends: Trends over time in elections.
-   Predictions: Differences between predicted and actual election results.

### Ethical Considerations 

In our analysis, we are utilizing existing data; however, it's important to recognize that the racial identities recorded in the dataset may not fully capture individuals' self-identifications. Quantitative categorizations often oversimplify the nuanced nature of social identities. Additionally, the historical understanding of race in Western societies has been primarily based on perceived anatomical distinctions. While contemporary knowledge recognizes that racial categorizations are socially constructed, the prevalence of biological interpretations persists within society (Oyěwùmí, 1997). 

Attributing certain behaviors or traits to a group of people based solely on shared physical characteristics has the potential to perpetuate harm. That being said, **causal relationships should not be drawn from the data**.

### Conclusions

We observe that political opinion in each state has varied widely since 1976. For example, California voted for the Republican nominee for president in 1976, 1980, 1984, and 1988, but it is now a Democratic stronghold. Arkansas was a swing state until the 2000 election but has since become a Republican stronghold. Other states, like Minnesota and Oklahoma, have consistently voted for the same political party since 1976—Democratic and Republican, respectively. We see that political opinion across the country has fluctuated significantly over the last 12 elections.

There are two primary takeaways from our exploration of how demographic patterns impact U.S. Presidential Election results. Firstly, and most importantly, demographic trends alone cannot fully explain voting patterns. Our model assumes that predominantly white, racially homogeneous states will consistently vote Republican, while diverse states will consistently vote Democrat. This assumption fails to account for regional variations, such as the broad liberal tendencies in New England and the strong conservative cores in southern states.

In every election year, our model overpredicts Republican performance. However, it appears that the model becomes slightly more accurate over time. In particular, it nearly perfectly predicts the results of the 2016 election. This may suggest that American partisan preferences are becoming increasingly divided along racial lines, especially with the arrival of Trump. However, as previously stated, no causal conclusions can be drawn from this analysis.

\

### References

MIT Election Data and Science Lab. (n.d.). Election Data. Retrieved from <https://electionlab.mit.edu/data>

National Conference of State Legislatures (NCSL). (n.d.). Election Administration at State and Local Levels. Retrieved from <https://www.ncsl.org/elections-and-campaigns/election-administration-at-state-and-local-levels>

Oyèrónkẹ́ Oyěwùmí. (1997). The Invention of Women: Making an African Sense of Western Gender Discourses. University of Minnesota Press.

### About This Project

Completed by Emanuel Deleon Otazu, Rylan Mueller, and Brian Pryzby for the Intermediate Data Science course at Macalester College. Inspired by our group’s personal interest in American politics, we were interested in exploring possible relationships between demographic information such as race/ethinicty and electoral politics. 




